### ISSUE TITLE
Store Instagram pictures

### ISSUE THREAD

**Issue by Nils85** [wuwanahq/wuwana2#179]
We currently rely on Instagram static servers to display all pictures from Instagram.
The problem is these image links are temporary and when they are outdated or if the user delete it our profile page becomes completely broken. Same for the company logo...

So instead of just storing links after scraping a profile we should download each picture from the link then keep them on our server until the next profile update.

**Comment by Nils85** [comment]
@levogirar You should remove all JavaScript code that replace missing images by the Wuwana logo in `main.js` with your **next** pull request

**Comment by levogirar** [comment]
I am not sure storing the pictures is a good solution. 
- If the user delete the picture form their instagram, I'd prefer to not show that picture on our website. 
- Wouldn't it cause us more problem with Instagram? I think following Google Images style would be better (do they store the picture in their servers?)
- I think this is only a problem because we do not update the companies frequently enough. A weekly link scraping should prevent this problem.

We can set this to cycle 6 #177 where we will focus on Instagram, Instagram, and Google. We can have `develop-v22` public and start the new `develop branch`

**Comment by Nils85** [comment]
> Wouldn't it cause us more problem with Instagram? I think following Google Images style would be better (do they store the picture in their servers?)

Technically it is way better for the website in order to becomes more stable. But legally it is definitely worst. 😅
Google Image never display pictures from Instagram and for others websites they do like us with a direct link from the origin website.

> I think this is only a problem because we do not update the companies frequently enough. A weekly link scraping should prevent this problem.

Not really because we are 100% dependent of Instagram servers. The moment we get blocked, whatever the update frequency is, we have to wait until Instagram decides to allow us to continue a little bit. And this is not going to improve with time because imagine in the future when we will have to update thousands of companies... So don't hope to have profile pages up to date with so many requests pending on Instagram.

> We can set this to cycle 6 #177 where we will focus on Instagram, Instagram, and Google. We can have `develop-v22` public and start the new `develop branch`

Ok but we have to know which path we are taking now:

- Continuing like that and dealing with dead links (not even for company logos)
- Caching all pictures from Instagram temporarily

**Comment by Nils85** [comment]
This is not a good solution. See related issue #183
